name: Attach build artifacts to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Inno Setup
        run: choco install innosetup -y
        shell: powershell

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { python -m pip install -r requirements.txt }
          python -m pip install pyinstaller==5.11.0
        shell: powershell

      - name: Generate PAC
        run: python src/generate_pac.py

      - name: Build with PyInstaller
        run: pyinstaller zapret_proxy_simple.spec
        shell: powershell

      - name: Build Inno Setup installer
        run: |
          $iscc = "C:\\Program Files (x86)\\Inno Setup 6\\ISCC.exe"
          & $iscc zapret_proxy_installer.iss
        shell: powershell

      - name: Upload installer to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/ZapretProxySetup.exe
          asset_name: ZapretProxySetup.exe
          asset_content_type: application/octet-stream
